#define PIN_LED_RED 2
#define PIN_LED_GREEN 3
#define PIN_LED_BLUE 4
#define PIN_LED_WHITE 5
#define PIN_LED_WARMWHITE 6

#define PIN_JOYSTICK_X A2
#define PIN_JOYSTICK_Y A3
#define PIN_JOYSTICK_SWITCH 26

#define PIN_CLOCK_DEBUG 50

// TX2
#define PIN_WIFI_TX 16
// RX2
#define PIN_WIFI_RX 17
#define PIN_WIFI_HAS_NEW_DATA 18
#define PIN_WIFI_RESET 34

#define PIN_LCD_BRIGHTNESS 9
